"""
Board routing table â€” generated from board_routing_master.csv.

Maps (state_abbr, psv_prov_type) -> [source_id, ...]
Multiple boards are tried in list order; first Pass wins.

  878 routing entries across 42 states and 44 provider types.
"""
from __future__ import annotations

# fmt: off
ROUTING: dict[tuple[str, str], list[str]] = {
    # AK
    ('AK', 'NP'): ['AK_CBP'],
    ('AK', 'NPB'): ['AK_CBP'],
    ('AK', 'PAS'): ['AK_CBP'],
    ('AK', 'PN'): ['AK_CBP'],
    ('AK', 'PT'): ['AK_CBP'],
    ('AK', 'SH'): ['AK_CBP'],

    # AL
    ('AL', 'AU'): ['AL_ABESPA'],
    ('AL', 'DO'): ['AL_ALBME'],
    ('AL', 'LC'): ['IBCLC_COMMISSION', 'AL_MFT'],
    ('AL', 'LPC'): ['AL_MFT'],
    ('AL', 'MD'): ['AL_ALBME'],
    ('AL', 'OD'): ['AL_OPTOMETRY'],
    ('AL', 'OP'): ['AL_OPTOMETRY'],
    ('AL', 'PA'): ['AL_ALBME'],
    ('AL', 'PAS'): ['AL_ALBME'],
    ('AL', 'SH'): ['AL_ABESPA'],

    # AR
    ('AR', 'ABA'): ['BACB'],
    ('AR', 'AU'): ['AR_ABESLPA'],
    ('AR', 'CP'): ['AR_APB'],
    ('AR', 'DAC'): ['AR_BEADAC'],
    ('AR', 'DC'): ['AR_ASBCE'],
    ('AR', 'DO'): ['AR_MEDBOARD'],
    ('AR', 'DT'): ['AR_DIETBOARD'],
    ('AR', 'DP'): ['AR_PODIATRY'],
    ('AR', 'GNC'): ['AR_MEDBOARD'],
    ('AR', 'LC'): ['IBCLC_COMMISSION', 'AR_ASBN'],
    ('AR', 'LPC'): ['AR_ABECMFT'],
    ('AR', 'MD'): ['AR_MEDBOARD'],
    ('AR', 'MT'): ['AR_ABECMFT'],
    ('AR', 'NP'): ['AR_ASBN'],
    ('AR', 'NPB'): ['AR_ASBN'],
    ('AR', 'NPS'): ['AR_ASBN'],
    ('AR', 'OD'): ['AR_ASBO'],
    ('AR', 'OP'): ['AR_ASBO'],
    ('AR', 'OT'): ['AR_MEDBOARD'],
    ('AR', 'PA'): ['AR_MEDBOARD'],
    ('AR', 'PAS'): ['AR_MEDBOARD'],
    ('AR', 'PE'): ['AR_APB'],
    ('AR', 'PH'): ['AR_MEDBOARD'],
    ('AR', 'PN'): ['AR_ASBN'],
    ('AR', 'PT'): ['AR_PTBS'],
    ('AR', 'RNA'): ['AR_ASBN'],
    ('AR', 'SH'): ['AR_ABESLPA'],
    ('AR', 'ST'): ['AR_ABESLPA'],
    ('AR', 'SW'): ['AR_SWB'],

    # AZ
    ('AZ', 'AU'): ['AZ_SPEECH_HEAR'],
    ('AZ', 'CP'): ['AZ_PSYCH'],
    ('AZ', 'DA'): ['AZ_DENTAL'],
    ('AZ', 'DAC'): ['AZ_BEHAVIORAL_HEALTH'],
    ('AZ', 'DC'): ['AZ_CHIRO'],
    ('AZ', 'DDS'): ['AZ_DENTAL'],
    ('AZ', 'DMD'): ['AZ_DENTAL'],
    ('AZ', 'DO'): ['AZ_OSTEO'],
    ('AZ', 'LAC'): ['AZ_ACUPUNCTURE'],
    ('AZ', 'LC'): ['IBCLC_COMMISSION', 'AZ_BEHAVIORAL_HEALTH'],
    ('AZ', 'LPC'): ['AZ_BEHAVIORAL_HEALTH'],
    ('AZ', 'MD'): ['AZ_MEDBOARD'],
    ('AZ', 'ND'): ['AZ_NATUROPATHIC'],
    ('AZ', 'OD'): ['AZ_OPTOMETRY'],
    ('AZ', 'OP'): ['AZ_OPTOMETRY'],
    ('AZ', 'OT'): ['AZ_OT'],
    ('AZ', 'PA'): ['AZ_MEDBOARD'],
    ('AZ', 'PAB'): ['AZ_MEDBOARD'],
    ('AZ', 'PAS'): ['AZ_MEDBOARD'],
    ('AZ', 'PT'): ['AZ_PT'],
    ('AZ', 'SH'): ['AZ_SPEECH_HEAR'],
    ('AZ', 'SW'): ['AZ_BEHAVIORAL_HEALTH'],

    # CO
    ('CO', 'ABA'): ['CO_DORA'],
    ('CO', 'CP'): ['CO_DORA', 'PSYPACT'],
    ('CO', 'AP'): ['CO_DORA'],
    ('CO', 'AU'): ['CO_DORA'],
    ('CO', 'DDS'): ['CO_DORA'],
    ('CO', 'DMD'): ['CO_DORA'],
    ('CO', 'DO'): ['CO_DORA'],
    ('CO', 'DP'): ['CO_DORA'],
    ('CO', 'DT'): ['CO_DORA'],
    ('CO', 'LC'): ['IBCLC_COMMISSION', 'CO_DORA'],
    ('CO', 'LPC'): ['CO_DORA'],
    ('CO', 'MD'): ['CO_DORA'],
    ('CO', 'MT'): ['CO_DORA'],
    ('CO', 'ND'): ['CO_DORA'],
    ('CO', 'NP'): ['CO_DORA'],
    ('CO', 'NPB'): ['CO_DORA'],
    ('CO', 'NUT'): ['CO_DORA'],
    ('CO', 'OT'): ['CO_DORA'],
    ('CO', 'PA'): ['CO_DORA'],
    ('CO', 'PAB'): ['CO_DORA'],
    ('CO', 'PAS'): ['CO_DORA'],
    ('CO', 'PH'): ['CO_DORA'],
    ('CO', 'PN'): ['CO_DORA'],
    ('CO', 'PT'): ['CO_DORA'],
    ('CO', 'RFA'): ['CO_DORA'],
    ('CO', 'RNA'): ['CO_DORA'],
    ('CO', 'SH'): ['CO_DORA'],
    ('CO', 'SW'): ['CO_DORA'],

    # CT
    ('CT', 'ABA'): ['CT_ELICENSE'],
    ('CT', 'AP'): ['CT_ELICENSE'],
    ('CT', 'AU'): ['CT_ELICENSE'],
    ('CT', 'CP'): ['CT_ELICENSE'],
    ('CT', 'DAC'): ['CT_ELICENSE'],
    ('CT', 'DC'): ['CT_ELICENSE'],
    ('CT', 'DO'): ['CT_ELICENSE'],
    ('CT', 'DP'): ['CT_ELICENSE'],
    ('CT', 'DT'): ['CT_ELICENSE'],
    ('CT', 'LC'): ['IBCLC_COMMISSION', 'CT_ELICENSE'],
    ('CT', 'LPC'): ['CT_ELICENSE'],
    ('CT', 'MD'): ['CT_ELICENSE'],
    ('CT', 'MT'): ['CT_ELICENSE'],
    ('CT', 'NP'): ['CT_ELICENSE'],
    ('CT', 'NPB'): ['CT_ELICENSE'],
    ('CT', 'NPS'): ['CT_ELICENSE'],
    ('CT', 'NUT'): ['CT_ELICENSE'],
    ('CT', 'OD'): ['CT_ELICENSE'],
    ('CT', 'OP'): ['CT_ELICENSE'],
    ('CT', 'OT'): ['CT_ELICENSE'],
    ('CT', 'PA'): ['CT_ELICENSE'],
    ('CT', 'PAS'): ['CT_ELICENSE'],
    ('CT', 'PH'): ['CT_ELICENSE'],
    ('CT', 'PN'): ['CT_ELICENSE'],
    ('CT', 'PT'): ['CT_ELICENSE'],
    ('CT', 'RNA'): ['CT_ELICENSE'],
    ('CT', 'SH'): ['CT_ELICENSE'],
    ('CT', 'ST'): ['CT_ELICENSE'],
    ('CT', 'SW'): ['CT_ELICENSE'],

    # FL
    ('FL', 'ABA'): ['BACB'],
    ('FL', 'AP'): ['FL_MQA'],
    ('FL', 'AU'): ['FL_MQA'],
    ('FL', 'CP'): ['FL_MQA'],
    ('FL', 'DC'): ['FL_MQA'],
    ('FL', 'DDS'): ['FL_MQA'],
    ('FL', 'DMD'): ['FL_MQA'],
    ('FL', 'DO'): ['FL_MQA'],
    ('FL', 'DP'): ['FL_MQA'],
    ('FL', 'DT'): ['FL_MQA'],
    ('FL', 'GNC'): ['FL_MQA'],
    ('FL', 'LC'): ['IBCLC_COMMISSION', 'FL_MQA'],
    ('FL', 'LPC'): ['FL_MQA'],
    ('FL', 'MD'): ['FL_MQA'],
    ('FL', 'MT'): ['FL_MQA'],
    ('FL', 'MW'): ['FL_MQA'],
    ('FL', 'NP'): ['FL_MQA'],
    ('FL', 'NPB'): ['FL_MQA'],
    ('FL', 'NPS'): ['FL_MQA'],
    ('FL', 'OD'): ['FL_MQA'],
    ('FL', 'OP'): ['FL_MQA'],
    ('FL', 'OT'): ['FL_MQA'],
    ('FL', 'PA'): ['FL_MQA'],
    ('FL', 'PAB'): ['FL_MQA'],
    ('FL', 'PAS'): ['FL_MQA'],
    ('FL', 'PH'): ['FL_MQA'],
    ('FL', 'PN'): ['FL_MQA'],
    ('FL', 'PT'): ['FL_MQA'],
    ('FL', 'RNA'): ['FL_MQA'],
    ('FL', 'SH'): ['FL_MQA'],
    ('FL', 'ST'): ['FL_MQA'],
    ('FL', 'SW'): ['FL_MQA'],

    # HI
    ('HI', 'DT'): ['HI_DIETITIANS'],

    # ID
    ('ID', 'ABA'): ['ID_DOPL'],
    ('ID', 'AP'): ['ID_DOPL'],   # FIX: added AP (Acupuncturist) routing â€” was causing no_routing fail (Aarush: see PSV run 20260813)
    ('ID', 'AU'): ['ID_DOPL'],
    ('ID', 'CP'): ['ID_DOPL'],
    ('ID', 'DC'): ['ID_DOPL'],
    ('ID', 'DO'): ['ID_DOPL'],
    ('ID', 'DP'): ['ID_DOPL'],
    ('ID', 'DT'): ['ID_DOPL'],
    ('ID', 'LC'): ['IBCLC_COMMISSION', 'ID_DOPL'],
    ('ID', 'LPC'): ['ID_DOPL'],
    ('ID', 'MD'): ['ID_DOPL'],
    ('ID', 'MT'): ['ID_DOPL'],
    ('ID', 'MW'): ['ID_DOPL'],
    ('ID', 'NP'): ['ID_DOPL'],
    ('ID', 'OD'): ['ID_DOPL'],
    ('ID', 'OP'): ['ID_DOPL'],
    ('ID', 'OT'): ['ID_DOPL'],
    ('ID', 'PA'): ['ID_DOPL'],
    ('ID', 'PAB'): ['ID_DOPL'],  # FIX: added PAB routing â€” input uses PAB but table only had PA; caused no_routing fail (Aarush: see PSV run 20260813)
    ('ID', 'PAS'): ['ID_DOPL'],
    ('ID', 'PH'): ['ID_DOPL'],
    ('ID', 'PN'): ['ID_DOPL'],
    ('ID', 'PT'): ['ID_DOPL'],
    ('ID', 'SH'): ['ID_DOPL'],
    ('ID', 'SW'): ['ID_DOPL'],

    # IL
    ('IL', 'ABA'): ['IL_LICENSING'],
    ('IL', 'AP'): ['IL_LICENSING'],
    ('IL', 'AU'): ['IL_LICENSING'],
    ('IL', 'CP'): ['IL_LICENSING'],
    ('IL', 'DAC'): ['IL_LICENSING'],
    ('IL', 'DC'): ['IL_LICENSING'],
    ('IL', 'DDS'): ['IL_LICENSING'],
    ('IL', 'DMD'): ['IL_LICENSING'],
    ('IL', 'DO'): ['IL_LICENSING'],
    ('IL', 'DP'): ['IL_LICENSING'],
    ('IL', 'DT'): ['IL_LICENSING'],
    ('IL', 'LC'): ['IBCLC_COMMISSION', 'IL_LICENSING'],
    ('IL', 'LPC'): ['IL_LICENSING'],
    ('IL', 'MD'): ['IL_LICENSING'],
    ('IL', 'MT'): ['IL_LICENSING'],
    ('IL', 'MW'): ['IL_LICENSING'],
    ('IL', 'NP'): ['IL_LICENSING'],
    ('IL', 'NPB'): ['IL_LICENSING'],
    ('IL', 'NPS'): ['IL_LICENSING'],
    ('IL', 'NSA'): ['IL_LICENSING'],
    ('IL', 'OD'): ['IL_LICENSING'],
    ('IL', 'OP'): ['IL_LICENSING'],
    ('IL', 'OT'): ['IL_LICENSING'],
    ('IL', 'PA'): ['IL_LICENSING'],
    ('IL', 'PAB'): ['IL_LICENSING'],
    ('IL', 'PAS'): ['IL_LICENSING'],
    ('IL', 'PH'): ['IL_LICENSING'],
    ('IL', 'PN'): ['IL_LICENSING'],
    ('IL', 'PT'): ['IL_LICENSING'],
    ('IL', 'RN'): ['IL_LICENSING'],
    ('IL', 'RNA'): ['IL_LICENSING'],
    ('IL', 'SH'): ['IL_LICENSING'],
    ('IL', 'SW'): ['IL_LICENSING'],

    # IN
    ('IN', 'ABA'): ['IN_PLA', 'BACB'],
    ('IN', 'AP'): ['IN_PLA'],
    ('IN', 'AU'): ['IN_PLA'],
    ('IN', 'CP'): ['IN_PLA'],
    ('IN', 'DAC'): ['IN_PLA'],
    ('IN', 'DC'): ['IN_PLA'],
    ('IN', 'DO'): ['IN_PLA'],
    ('IN', 'DP'): ['IN_PLA'],
    ('IN', 'DT'): ['IN_PLA'],
    ('IN', 'LC'): ['IBCLC_COMMISSION', 'IN_PLA'],
    ('IN', 'LPC'): ['IN_PLA'],
    ('IN', 'MD'): ['IN_PLA'],
    ('IN', 'MT'): ['IN_PLA'],
    ('IN', 'NP'): ['IN_PLA'],
    ('IN', 'NPB'): ['IN_PLA'],
    ('IN', 'NPS'): ['IN_PLA'],
    ('IN', 'OD'): ['IN_PLA'],
    ('IN', 'OP'): ['IN_PLA'],
    ('IN', 'OT'): ['IN_PLA'],
    ('IN', 'PA'): ['IN_PLA'],
    ('IN', 'PAS'): ['IN_PLA'],
    ('IN', 'PH'): ['IN_PLA'],
    ('IN', 'PN'): ['IN_PLA'],
    ('IN', 'PT'): ['IN_PLA'],
    ('IN', 'RNA'): ['IN_PLA'],
    ('IN', 'SH'): ['IN_PLA'],
    ('IN', 'SW'): ['IN_PLA'],

    # KS
    ('KS', 'ABA'): ['KS_BSRB'],
    ('KS', 'CP'): ['KS_BSRB'],
    ('KS', 'DA'): ['KS_DENTAL'],
    ('KS', 'DC'): ['KS_KSBHADA'],
    ('KS', 'DDS'): ['KS_DENTAL'],
    ('KS', 'DMD'): ['KS_DENTAL'],
    ('KS', 'DN'): ['KS_KSBHADA'],
    ('KS', 'DP'): ['KS_PHARMACY'],
    ('KS', 'DT'): ['KS_GLSUITE', 'KS_KSBHADA'],
    ('KS', 'LC'): ['IBCLC_COMMISSION', 'KS_NURSING_KSBN', 'KS_BSRB'],
    ('KS', 'LPC'): ['KS_BSRB'],
    ('KS', 'MT'): ['KS_BSRB'],
    ('KS', 'MW'): ['KS_KSBHADA'],
    ('KS', 'NP'): ['KS_NURSING_KSBN'],
    ('KS', 'NPB'): ['KS_NURSING_KSBN'],
    ('KS', 'NPS'): ['KS_NURSING_KSBN'],
    ('KS', 'NSA'): ['KS_NURSING_KSBN'],
    ('KS', 'OD'): ['KS_OPTOMETRY'],
    ('KS', 'OP'): ['KS_OPTOMETRY'],
    ('KS', 'OT'): ['KS_KSBHADA'],
    ('KS', 'PAB'): ['KS_KSBHADA', 'KS_GLSUITE'],
    ('KS', 'PAS'): ['KS_KSBHADA', 'KS_GLSUITE'],
    ('KS', 'PH'): ['KS_PHARMACY'],
    ('KS', 'PN'): ['KS_NURSING_KSBN'],
    ('KS', 'PT'): ['KS_KSBHADA'],
    ('KS', 'RN'): ['KS_NURSING_KSBN'],
    ('KS', 'RNA'): ['KS_NURSING_KSBN', 'KS_GLSUITE'],
    ('KS', 'SH'): ['KS_GLSUITE', 'KS_KSBHADA'],
    ('KS', 'SW'): ['KS_BSRB'],

    # KY
    ('KY', 'ABA'): ['KY_MULTIBOARD'],
    ('KY', 'AP'): ['KY_AP'],
    ('KY', 'AU'): ['KY_MULTIBOARD'],
    ('KY', 'CP'): ['KY_MULTIBOARD'],
    ('KY', 'DC'): ['KY_MULTIBOARD'],
    ('KY', 'DN'): ['KY_DENTAL'],
    ('KY', 'DO'): ['KY_MEDBOARD'],
    ('KY', 'DP'): ['KY_MULTIBOARD'],
    ('KY', 'DT'): ['KY_MULTIBOARD'],
    ('KY', 'GNC'): ['KY_GC'],
    ('KY', 'LAC'): ['KY_AP'],
    ('KY', 'LC'): ['IBCLC_COMMISSION', 'KY_MULTIBOARD'],
    ('KY', 'LPC'): ['KY_MULTIBOARD'],
    ('KY', 'MD'): ['KY_MEDBOARD'],
    ('KY', 'MT'): ['KY_MULTIBOARD'],
    ('KY', 'OD'): ['KY_OD'],
    ('KY', 'OP'): ['KY_OD'],
    ('KY', 'OT'): ['KY_MULTIBOARD'],
    ('KY', 'PA'): ['KY_PA'],
    ('KY', 'PAB'): ['KY_PA'],
    ('KY', 'PAS'): ['KY_PA'],
    ('KY', 'PH'): ['KY_PHARMACY'],
    ('KY', 'PM'): ['KY_PHARMACY'],
    ('KY', 'PT'): ['KY_MULTIBOARD'],
    ('KY', 'SA'): ['KY_SA'],
    ('KY', 'SH'): ['KY_MULTIBOARD'],
    ('KY', 'ST'): ['KY_MULTIBOARD'],
    ('KY', 'SW'): ['KY_MULTIBOARD'],

    # LA
    ('LA', 'AU'): ['LA_SPEECH'],
    ('LA', 'DA'): ['LA_DENTAL'],
    ('LA', 'DDS'): ['LA_DENTAL'],
    ('LA', 'DMD'): ['LA_DENTAL'],
    ('LA', 'DO'): ['LA_MEDBOARD'],
    ('LA', 'DT'): ['LA_DIETETICS'],
    ('LA', 'MD'): ['LA_MEDBOARD'],
    ('LA', 'MT'): ['LA_MASSAGETHERAPY'],
    ('LA', 'OD'): ['LA_OPTOMETRY'],
    ('LA', 'OP'): ['LA_OPTOMETRY'],
    ('LA', 'OT'): ['LA_MEDBOARD'],
    ('LA', 'PA'): ['LA_MEDBOARD'],
    ('LA', 'PAS'): ['LA_MEDBOARD'],
    ('LA', 'PT'): ['LA_PT'],
    ('LA', 'SH'): ['LA_SPEECH'],
    ('LA', 'SW'): ['LA_SOCIALWORK'],

    # MA
    ('MA', 'ABA'): ['MA_HEALTH'],
    ('MA', 'AP'): ['MA_HEALTH'],
    ('MA', 'AU'): ['MA_HEALTH'],
    ('MA', 'CP'): ['MA_HEALTH', 'PSYPACT'],
    ('MA', 'DAC'): ['MA_BSAS'],
    ('MA', 'DC'): ['MA_HEALTH'],
    ('MA', 'DO'): ['MA_MDDO'],
    ('MA', 'DP'): ['MA_HEALTH'],
    ('MA', 'DT'): ['MA_HEALTH'],
    ('MA', 'LC'): ['IBCLC_COMMISSION', 'MA_HEALTH'],
    ('MA', 'LPC'): ['MA_HEALTH'],
    ('MA', 'MD'): ['MA_MDDO'],
    ('MA', 'MW'): ['MA_HEALTH'],
    ('MA', 'NP'): ['MA_HEALTH'],
    ('MA', 'NPB'): ['MA_HEALTH'],
    ('MA', 'NPS'): ['MA_HEALTH'],
    ('MA', 'NUT'): ['MA_HEALTH'],
    ('MA', 'OP'): ['MA_HEALTH'],
    ('MA', 'OT'): ['MA_HEALTH'],
    ('MA', 'PA'): ['MA_HEALTH'],
    ('MA', 'PAS'): ['MA_HEALTH'],
    ('MA', 'PH'): ['MA_MDDO', 'MA_HEALTH'],
    ('MA', 'PN'): ['MA_HEALTH'],
    ('MA', 'PT'): ['MA_HEALTH'],
    ('MA', 'RN'): ['MA_HEALTH'],
    ('MA', 'RNA'): ['MA_HEALTH'],
    ('MA', 'SH'): ['MA_HEALTH'],
    ('MA', 'SW'): ['MA_HEALTH'],

    # MD
    ('MD', 'AP'): ['MD_ACUPUNCTURE'],
    ('MD', 'AU'): ['MD_AUDIOLOGY'],
    ('MD', 'CP'): ['MD_PSYCH'],
    ('MD', 'DC'): ['MD_CHIROPRACTIC'],
    ('MD', 'DO'): ['MD_PHYSICIANS'],
    ('MD', 'DT'): ['MD_DIETETICS'],
    ('MD', 'LAC'): ['MD_ACUPUNCTURE'],
    ('MD', 'LC'): ['IBCLC_COMMISSION', 'MD_NURSING', 'MD_COUNSELORS'],
    ('MD', 'LPC'): ['MD_COUNSELORS'],
    ('MD', 'MD'): ['MD_PHYSICIANS'],
    ('MD', 'NP'): ['MD_NURSING'],
    ('MD', 'NPB'): ['MD_NURSING'],
    ('MD', 'NPS'): ['MD_NURSING'],
    ('MD', 'PH'): ['MD_PHYSICIANS'],
    ('MD', 'MT'): ['MD_MASSAGE'],
    ('MD', 'PN'): ['MD_NURSING'],
    ('MD', 'RNA'): ['MD_NURSING'],
    ('MD', 'OD'): ['MD_OPTOMETRY'],
    ('MD', 'OP'): ['MD_OPTOMETRY'],
    ('MD', 'PA'): ['MD_PHYSICIANS'],
    ('MD', 'PAS'): ['MD_PHYSICIANS'],
    ('MD', 'PT'): ['MD_PT'],
    ('MD', 'SH'): ['MD_AUDIOLOGY'],
    ('MD', 'SW'): ['MD_SOCIALWORK'],

    # ME
    ('ME', 'ABA'): ['ME_OPLR'],
    ('ME', 'AU'): ['ME_OPLR'],
    ('ME', 'DA'): ['ME_OPLR'],
    ('ME', 'DAC'): ['ME_OPLR'],
    ('ME', 'DC'): ['ME_OPLR'],
    ('ME', 'DDS'): ['ME_OPLR'],
    ('ME', 'DMD'): ['ME_OPLR'],
    ('ME', 'DO'): ['ME_OPLR'],
    ('ME', 'DT'): ['ME_OPLR'],
    ('ME', 'LC'): ['IBCLC_COMMISSION', 'ME_OPLR'],
    ('ME', 'LPC'): ['ME_OPLR'],
    ('ME', 'MD'): ['ME_OPLR'],
    ('ME', 'MT'): ['ME_OPLR'],
    ('ME', 'NP'): ['ME_OPLR'],
    ('ME', 'NPB'): ['ME_OPLR'],
    ('ME', 'NPS'): ['ME_OPLR'],
    ('ME', 'OT'): ['ME_OPLR'],
    ('ME', 'PH'): ['ME_OPLR'],
    ('ME', 'PN'): ['ME_OPLR'],
    ('ME', 'PT'): ['ME_OPLR'],
    ('ME', 'RNA'): ['ME_OPLR'],
    ('ME', 'SH'): ['ME_OPLR'],
    ('ME', 'SW'): ['ME_OPLR'],

    # MI
    ('MI', 'ABA'): ['MI_LARA'],
    ('MI', 'AP'): ['MI_LARA'],
    ('MI', 'AU'): ['MI_LARA'],
    ('MI', 'CP'): ['MI_LARA'],
    ('MI', 'DC'): ['MI_LARA'],
    ('MI', 'DDS'): ['MI_LARA'],
    ('MI', 'DMD'): ['MI_LARA'],
    ('MI', 'DO'): ['MI_LARA'],
    ('MI', 'DP'): ['MI_LARA'],
    ('MI', 'DT'): ['MI_LARA'],
    ('MI', 'LC'): ['IBCLC_COMMISSION', 'MI_LARA'],
    ('MI', 'LPC'): ['MI_LARA'],
    ('MI', 'LPN'): ['MI_LARA'],
    ('MI', 'MD'): ['MI_LARA'],
    ('MI', 'MT'): ['MI_LARA'],
    ('MI', 'MW'): ['MI_LARA'],
    ('MI', 'NP'): ['MI_LARA'],
    ('MI', 'NPB'): ['MI_LARA'],
    ('MI', 'NPS'): ['MI_LARA'],
    ('MI', 'NUT'): ['MI_LARA'],
    ('MI', 'OD'): ['MI_LARA'],
    ('MI', 'OP'): ['MI_LARA'],
    ('MI', 'OT'): ['MI_LARA'],
    ('MI', 'PA'): ['MI_LARA'],
    ('MI', 'PAS'): ['MI_LARA'],
    ('MI', 'PH'): ['MI_LARA'],
    ('MI', 'PN'): ['MI_LARA'],
    ('MI', 'PT'): ['MI_LARA'],
    ('MI', 'RN'): ['MI_LARA'],
    ('MI', 'RNA'): ['MI_LARA'],
    ('MI', 'SW'): ['MI_LARA'],
    ('MI', 'SH'): ['MI_LARA'],

    # MN
    ('MN', 'AP'): ['MN_MEDPRACTICE'],
    ('MN', 'DA'): ['MN_DENTISTRY'],
    ('MN', 'DDS'): ['MN_DENTISTRY'],
    ('MN', 'DMD'): ['MN_DENTISTRY'],
    ('MN', 'DO'): ['MN_MEDPRACTICE'],
    ('MN', 'MD'): ['MN_MEDPRACTICE'],
    ('MN', 'NP'): ['MN_MEDPRACTICE'],
    ('MN', 'NPB'): ['MN_MEDPRACTICE'],
    ('MN', 'NPS'): ['MN_MEDPRACTICE'],
    ('MN', 'PA'): ['MN_MEDPRACTICE'],
    ('MN', 'PAS'): ['MN_MEDPRACTICE'],

    # MO
    ('MO', 'AP'): ['MO_NURSING'],
    ('MO', 'CP'): ['MO_PSYCHOLOGISTS'],
    ('MO', 'DA'): ['MO_DENTAL'],
    ('MO', 'DC'): ['MO_CHIROPRACTIC'],
    ('MO', 'DDS'): ['MO_DENTAL'],
    ('MO', 'DMD'): ['MO_DENTAL'],
    ('MO', 'DO'): ['MO_HEALING_ARTS'],
    ('MO', 'DP'): ['MO_PHARMACY'],
    ('MO', 'MD'): ['MO_HEALING_ARTS'],
    ('MO', 'NP'): ['MO_NURSING'],
    ('MO', 'NPB'): ['MO_NURSING'],
    ('MO', 'NPS'): ['MO_NURSING'],
    ('MO', 'OD'): ['MO_OPTOMETRY'],
    ('MO', 'OP'): ['MO_OPTOMETRY'],
    ('MO', 'PA'): ['MO_HEALING_ARTS'],
    ('MO', 'PAS'): ['MO_HEALING_ARTS'],
    ('MO', 'PH'): ['MO_PHARMACY'],
    ('MO', 'PN'): ['MO_NURSING'],
    ('MO', 'RNA'): ['MO_NURSING'],

    # MS
    ('MS', 'ABA'): ['MS_ABA'],
    ('MS', 'AU'): ['MS_DHPL'],
    ('MS', 'CP'): ['MS_PSYCH'],
    ('MS', 'DC'): ['MS_CHIRO'],
    ('MS', 'DT'): ['MS_DHPL'],
    ('MS', 'LC'): ['IBCLC_COMMISSION', 'MS_LPC', 'MS_DHPL', 'MS_SWMFT'],
    ('MS', 'LPC'): ['MS_LPC', 'MS_DHPL', 'MS_SWMFT'],
    ('MS', 'MT'): ['MS_DHPL'],
    ('MS', 'NP'): ['MS_DHPL'],
    ('MS', 'NPB'): ['MS_DHPL'],
    ('MS', 'OD'): ['MS_OPTOMETRY'],
    ('MS', 'OP'): ['MS_OPTOMETRY'],
    ('MS', 'OT'): ['MS_DHPL'],
    ('MS', 'PN'): ['MS_DHPL'],
    ('MS', 'PT'): ['MS_PT'],
    ('MS', 'SH'): ['MS_DHPL'],
    ('MS', 'SW'): ['MS_SWMFT'],

    # NC
    ('NC', 'AU'): ['NC_SLP_AUD'],
    ('NC', 'CP'): ['NC_MENTAL_HEALTH'],
    ('NC', 'DA'): ['NC_DENTAL'],
    ('NC', 'DAC'): ['NC_DAC'],
    ('NC', 'DC'): ['NC_CHIRO'],
    ('NC', 'DDS'): ['NC_DENTAL'],
    ('NC', 'DMD'): ['NC_DENTAL'],
    ('NC', 'DP'): ['NC_PODIATRY'],
    ('NC', 'DT'): ['NC_DIETETICS'],
    ('NC', 'LC'): ['IBCLC_COMMISSION', 'NC_MENTAL_HEALTH', 'NC_DAC'],
    # LPC providers may hold an addiction-counselor (LCAS) credential regulated by
    # the NC Substance Abuse Professional Practice Board (NC_DAC), not the mental
    # health counselors board. Try NC_MENTAL_HEALTH first, fall back to NC_DAC.
    # ('NC', 'LPC'): ['NC_MENTAL_HEALTH', 'NC_DAC'],
    ('NC', 'MT'): ['NC_MASSAGE'],
    ('NC', 'NUT'): ['NC_DIETETICS'],
    ('NC', 'OD'): ['NC_OPTOMETRY'],
    ('NC', 'OP'): ['NC_OPTOMETRY'],
    # OR = oral / maxillofacial surgeon â€” verified at the NC dental board; fall
    # back to the medical board for dual-degree (MD) oral surgeons.
    ('NC', 'OR'): ['NC_DENTAL', 'NC_MEDBOARD'],
    ('NC', 'LPC'): ['NC_MENTAL_HEALTH', 'NC_DAC'],  # LCAS holders may be verified via NC_DAC
    ('NC', 'NUT'): ['NC_DIETETICS'],
    ('NC', 'OD'): ['NC_OPTOMETRY'],
    ('NC', 'OP'): ['NC_OPTOMETRY'],
    # ('NC', 'OR'): ['NC_MEDBOARD', 'NC_DENTAL'],
    ('NC', 'OT'): ['NC_OT'],
    # PC = pastoral counselor â€” certified by the NC Board of Pastoral Counseling
    # (small integer certificate numbers, e.g. 83/122), NOT the addiction board.
    ('NC', 'PC'): ['NC_PASTORAL_COUNSELING'],
    ('NC', 'PT'): ['NC_PT'],
    ('NC', 'SH'): ['NC_SLP_AUD'],
    ('NC', 'ST'): ['NC_SLP_AUD'],

    # ND
    ('ND', 'ABA'): ['ND_AP'],
    ('ND', 'AP'): ['ND_AP'],
    ('ND', 'DA'): ['ND_DENTISTRY'],
    ('ND', 'DDS'): ['ND_DENTISTRY'],
    ('ND', 'DMD'): ['ND_DENTISTRY'],
    ('ND', 'DP'): ['ND_PODIATRY'],
    ('ND', 'MT'): ['ND_AP'],
    ('ND', 'PT'): ['ND_PT'],

    # NH
    ('NH', 'ABA'): ['NH_OPLC'],
    ('NH', 'AU'): ['NH_OPLC'],
    ('NH', 'CP'): ['NH_OPLC', 'PSYPACT'],
    ('NH', 'DAC'): ['NH_OPLC'],
    ('NH', 'DC'): ['NH_OPLC'],
    ('NH', 'DDS'): ['NH_OPLC'],
    ('NH', 'DMD'): ['NH_OPLC'],
    ('NH', 'DO'): ['NH_OPLC'],
    ('NH', 'DT'): ['NH_OPLC'],
    ('NH', 'LC'): ['IBCLC_COMMISSION', 'NH_OPLC'],
    ('NH', 'LPC'): ['NH_OPLC'],
    ('NH', 'MD'): ['NH_OPLC'],
    ('NH', 'NP'): ['NH_OPLC'],
    ('NH', 'NPB'): ['NH_OPLC'],
    ('NH', 'OD'): ['NH_OPLC'],
    ('NH', 'OP'): ['NH_OPLC'],
    ('NH', 'OT'): ['NH_OPLC'],
    ('NH', 'PA'): ['NH_OPLC'],
    ('NH', 'PAS'): ['NH_OPLC'],
    ('NH', 'PH'): ['NH_OPLC'],
    ('NH', 'PN'): ['NH_OPLC'],
    ('NH', 'PT'): ['NH_OPLC'],
    ('NH', 'RNA'): ['NH_OPLC'],
    ('NH', 'SH'): ['NH_OPLC'],
    ('NH', 'ST'): ['NH_OPLC'],
    ('NH', 'SW'): ['NH_OPLC'],

    # NJ
    ('NJ', 'ABA'): ['NJ_DCA'],
    ('NJ', 'AP'): ['NJ_DCA'],
    ('NJ', 'AU'): ['NJ_DCA'],
    ('NJ', 'CP'): ['NJ_DCA'],
    ('NJ', 'DC'): ['NJ_DCA'],
    ('NJ', 'DO'): ['NJ_DCA'],
    ('NJ', 'DT'): ['NJ_DCA'],
    ('NJ', 'GNC'): ['NJ_DCA'],
    ('NJ', 'LC'): ['IBCLC_COMMISSION', 'NJ_DCA'],
    ('NJ', 'LPC'): ['NJ_DCA'],
    ('NJ', 'MD'): ['NJ_DCA'],
    ('NJ', 'MT'): ['NJ_DCA'],
    ('NJ', 'NP'): ['NJ_DCA'],
    ('NJ', 'NPB'): ['NJ_DCA'],
    ('NJ', 'NPS'): ['NJ_DCA'],
    ('NJ', 'NUT'): ['NJ_DCA'],
    ('NJ', 'OD'): ['NJ_DCA'],
    ('NJ', 'OP'): ['NJ_DCA'],
    ('NJ', 'OT'): ['NJ_DCA'],
    ('NJ', 'PA'): ['NJ_DCA'],
    ('NJ', 'PAS'): ['NJ_DCA'],
    ('NJ', 'PH'): ['NJ_DCA'],
    ('NJ', 'PN'): ['NJ_DCA'],
    ('NJ', 'PT'): ['NJ_DCA'],
    ('NJ', 'RNA'): ['NJ_DCA'],
    ('NJ', 'SH'): ['NJ_DCA'],
    ('NJ', 'ST'): ['NJ_DCA'],
    ('NJ', 'SW'): ['NJ_DCA'],

    # NM
    ('NM', 'AU'): ['NM_RLD'],
    ('NM', 'DC'): ['NM_RLD'],
    ('NM', 'DDS'): ['NM_RLD'],
    ('NM', 'DMD'): ['NM_RLD'],
    ('NM', 'DO'): ['NM_MEDBOARD'],
    ('NM', 'DP'): ['NM_RLD'],
    ('NM', 'DT'): ['NM_RLD'],
    ('NM', 'LAC'): ['NM_RLD'],
    ('NM', 'MD'): ['NM_MEDBOARD'],
    ('NM', 'MT'): ['NM_RLD'],
    ('NM', 'MW'): ['NM_MIDWIVES'],
    ('NM', 'OD'): ['NM_RLD'],
    ('NM', 'OP'): ['NM_RLD'],
    ('NM', 'OT'): ['NM_RLD'],
    ('NM', 'PA'): ['NM_MEDBOARD'],
    ('NM', 'PAS'): ['NM_MEDBOARD'],
    ('NM', 'PT'): ['NM_RLD'],
    ('NM', 'SH'): ['NM_RLD'],

    # NV
    ('NV', 'ABA'): ['NV_ABA'],
    ('NV', 'AP'): ['NV_ORIENTAL'],
    ('NV', 'AU'): ['NV_SPEECH'],
    ('NV', 'CP'): ['NV_BOP'],
    ('NV', 'DA'): ['NV_NVADGC'],
    ('NV', 'DC'): ['NV_CHIRO'],
    ('NV', 'DDS'): ['NV_NVADGC', 'NV_DENTAL'],
    ('NV', 'DMD'): ['NV_NVADGC', 'NV_DENTAL'],
    ('NV', 'DO'): ['NV_MEDBOARD', 'NV_OSTEO'],
    ('NV', 'DP'): ['NV_PODIATRY'],
    ('NV', 'DT'): ['NV_DIETITIAN'],
    ('NV', 'LAC'): ['NV_ORIENTAL'],
    ('NV', 'LC'): ['IBCLC_COMMISSION', 'NV_MFTPC'],
    ('NV', 'LPC'): ['NV_MFTPC'],
    ('NV', 'MD'): ['NV_MEDBOARD'],
    ('NV', 'MST'): ['NV_MASSAGE'],
    ('NV', 'MT'): ['NV_MFTPC'],
    ('NV', 'MW'): ['NV_NURSING_BON'],
    ('NV', 'OD'): ['NV_OPTOMETRY'],
    ('NV', 'OP'): ['NV_OPTOMETRY'],
    ('NV', 'PA'): ['NV_MEDBOARD'],
    ('NV', 'PAS'): ['NV_MEDBOARD'],
    ('NV', 'PH'): ['NV_PHARMACY'],
    ('NV', 'PT'): ['NV_PT'],
    ('NV', 'SH'): ['NV_SPEECH'],
    ('NV', 'ST'): ['NV_SPEECH'],

    # NY
    ('NY', 'ABA'): ['NY_CREDENTIALS'],
    ('NY', 'AP'): ['NY_CREDENTIALS'],
    ('NY', 'AU'): ['NY_CREDENTIALS'],
    ('NY', 'CP'): ['NY_CREDENTIALS'],
    ('NY', 'DC'): ['NY_CREDENTIALS'],
    ('NY', 'DDS'): ['NY_CREDENTIALS'],
    ('NY', 'DMD'): ['NY_CREDENTIALS'],
    ('NY', 'DO'): ['NY_CREDENTIALS'],
    ('NY', 'DP'): ['NY_CREDENTIALS'],
    ('NY', 'DT'): ['NY_CREDENTIALS'],
    ('NY', 'LC'): ['IBCLC_COMMISSION', 'NY_CREDENTIALS'],
    ('NY', 'LPC'): ['NY_CREDENTIALS'],
    ('NY', 'MD'): ['NY_CREDENTIALS'],
    ('NY', 'MT'): ['NY_CREDENTIALS'],
    ('NY', 'MW'): ['NY_CREDENTIALS'],
    ('NY', 'NP'): ['NY_CREDENTIALS'],
    ('NY', 'NPB'): ['NY_CREDENTIALS'],
    ('NY', 'NPS'): ['NY_CREDENTIALS'],
    ('NY', 'NUT'): ['NY_CREDENTIALS'],
    ('NY', 'OP'): ['NY_CREDENTIALS'],
    ('NY', 'OT'): ['NY_CREDENTIALS'],
    ('NY', 'PAB'): ['NY_CREDENTIALS'],
    ('NY', 'PAS'): ['NY_CREDENTIALS'],
    ('NY', 'PH'): ['NY_CREDENTIALS'],
    ('NY', 'PN'): ['NY_CREDENTIALS'],
    ('NY', 'PT'): ['NY_CREDENTIALS'],
    ('NY', 'RNA'): ['NY_CREDENTIALS'],
    ('NY', 'SH'): ['NY_CREDENTIALS'],
    ('NY', 'ST'): ['NY_CREDENTIALS'],
    ('NY', 'SW'): ['NY_CREDENTIALS'],

    # OH
    ('OH', 'ABA'): ['OH_PROVIDERS_INDIVIDUAL'],
    ('OH', 'AP'): ['OH_PROVIDERS_INDIVIDUAL'],
    ('OH', 'AU'): ['OH_PROVIDERS_INDIVIDUAL'],
    ('OH', 'CP'): ['OH_PROVIDERS_INDIVIDUAL'],
    ('OH', 'DAC'): ['OH_PROVIDERS_INDIVIDUAL'],
    ('OH', 'DC'): ['OH_PROVIDERS_INDIVIDUAL'],
    ('OH', 'DP'): ['OH_PROVIDERS_INDIVIDUAL'],
    ('OH', 'DT'): ['OH_PROVIDERS_INDIVIDUAL'],
    ('OH', 'LC'): ['IBCLC_COMMISSION', 'OH_PROVIDERS_INDIVIDUAL'],
    ('OH', 'LPC'): ['OH_PROVIDERS_INDIVIDUAL'],
    ('OH', 'MST'): ['OH_PROVIDERS_INDIVIDUAL'],
    ('OH', 'MT'): ['OH_PROVIDERS_INDIVIDUAL'],
    ('OH', 'MW'): ['OH_PROVIDERS_INDIVIDUAL'],
    ('OH', 'NP'): ['OH_PROVIDERS_INDIVIDUAL'],
    ('OH', 'NPB'): ['OH_PROVIDERS_INDIVIDUAL'],
    ('OH', 'OT'): ['OH_PROVIDERS_INDIVIDUAL'],
    ('OH', 'PAB'): ['OH_PROVIDERS_INDIVIDUAL'],
    ('OH', 'PAS'): ['OH_PROVIDERS_INDIVIDUAL'],
    ('OH', 'PH'): ['OH_PROVIDERS_INDIVIDUAL'],
    ('OH', 'PN'): ['OH_PROVIDERS_INDIVIDUAL'],
    ('OH', 'PT'): ['OH_PROVIDERS_INDIVIDUAL'],
    ('OH', 'RNA'): ['OH_PROVIDERS_INDIVIDUAL'],
    ('OH', 'SH'): ['OH_PROVIDERS_INDIVIDUAL'],
    ('OH', 'SW'): ['OH_PROVIDERS_INDIVIDUAL'],

    # OK
    ('OK', 'AT'): ['OK_MEDBOARD'],
    ('OK', 'AU'): ['OK_SLP_AUD'],
    ('OK', 'CADC'): ['OK_ADAC'],
    ('OK', 'CADCI'): ['OK_ADAC'],
    ('OK', 'CNA'): ['OK_ODOHCS'],
    ('OK', 'DA'): ['OK_DENTAL'],
    ('OK', 'DAC'): ['OK_ADAC', 'OK_BEHAVIORAL_HEALTH'],
    ('OK', 'DDS'): ['OK_DENTAL'],
    ('OK', 'DMD'): ['OK_DENTAL'],
    ('OK', 'DO'): ['OK_OSTEO'],
    ('OK', 'DT'): ['OK_MEDBOARD'],
    ('OK', 'EMT'): ['OK_ODOHCS'],
    ('OK', 'HHA'): ['OK_ODOHCS'],
    ('OK', 'LADC-MH'): ['OK_ADAC'],
    ('OK', 'LBP'): ['OK_BEHAVIORAL_HEALTH'],
    ('OK', 'LC'): ['IBCLC_COMMISSION', 'OK_BEHAVIORAL_HEALTH'],
    ('OK', 'LD'): ['OK_MEDBOARD'],
    ('OK', 'LMFT'): ['OK_BEHAVIORAL_HEALTH'],
    ('OK', 'LPC'): ['OK_BEHAVIORAL_HEALTH'],
    ('OK', 'MD'): ['OK_MEDBOARD'],
    ('OK', 'OD'): ['OK_OPTOMETRY'],
    ('OK', 'OP'): ['OK_OPTOMETRY'],
    ('OK', 'OT'): ['OK_MEDBOARD'],
    ('OK', 'PA'): ['OK_MEDBOARD'],
    ('OK', 'PAB'): ['OK_MEDBOARD'],
    ('OK', 'PAS'): ['OK_MEDBOARD'],
    ('OK', 'PH'): ['OK_MEDBOARD'],
    ('OK', 'POD'): ['OK_MEDBOARD'],
    ('OK', 'PT'): ['OK_MEDBOARD'],
    ('OK', 'RC'): ['OK_MEDBOARD'],
    ('OK', 'RDH'): ['OK_DENTAL'],
    ('OK', 'SH'): ['OK_SLP_AUD'],
    ('OK', 'ST'): ['OK_SLP_AUD'],
    ('OK', 'SW'): ['OK_SOCIALWORK'],

    # OR
    ('OR', 'ABA'): ['OR_HLO'],
    ('OR', 'AU'): ['OR_SLP', 'OR_HLO'],
    ('OR', 'CP'): ['OR_PSYCH'],
    ('OR', 'DA'): ['OR_DENTAL'],
    ('OR', 'DDS'): ['OR_DENTAL'],
    ('OR', 'DMD'): ['OR_DENTAL'],
    ('OR', 'DO'): ['OR_OMB'],
    ('OR', 'DP'): ['OR_OMB'],
    ('OR', 'DT'): ['OR_HLO'],
    ('OR', 'LC'): ['IBCLC_COMMISSION', 'OR_COUNSELORS'],
    ('OR', 'LPC'): ['OR_COUNSELORS'],
    ('OR', 'MD'): ['OR_OMB'],
    ('OR', 'ND'): ['OR_NATUROPATH'],
    ('OR', 'NUT'): ['OR_HLO'],
    ('OR', 'OD'): ['OR_OPTOMETRY'],
    ('OR', 'OP'): ['OR_OPTOMETRY'],
    ('OR', 'OT'): ['OR_OT'],
    ('OR', 'PA'): ['OR_OMB'],
    ('OR', 'PAB'): ['OR_OMB'],
    ('OR', 'PAS'): ['OR_OMB'],
    ('OR', 'PT'): ['OR_PT'],
    ('OR', 'SH'): ['OR_SLP'],
    ('OR', 'ST'): ['OR_SLP'],

    # PA
    ('PA', 'ABA'): ['PA_PALS'],
    ('PA', 'AP'): ['PA_PALS'],
    ('PA', 'AU'): ['PA_PALS'],
    ('PA', 'CP'): ['PA_PALS'],
    ('PA', 'DA'): ['PA_PALS'],
    ('PA', 'DAC'): ['PA_PALS'],
    ('PA', 'DC'): ['PA_PALS'],
    ('PA', 'DDS'): ['PA_PALS'],
    ('PA', 'DMD'): ['PA_PALS'],
    ('PA', 'DO'): ['PA_PALS'],
    ('PA', 'DP'): ['PA_PALS'],
    ('PA', 'DT'): ['PA_PALS'],
    ('PA', 'LC'): ['IBCLC_COMMISSION', 'PA_PALS'],
    ('PA', 'LPC'): ['PA_PALS'],
    ('PA', 'MD'): ['PA_PALS'],
    ('PA', 'MT'): ['PA_PALS'],
    ('PA', 'MW'): ['PA_PALS'],
    ('PA', 'NP'): ['PA_PALS'],
    ('PA', 'NPB'): ['PA_PALS'],
    ('PA', 'NPS'): ['PA_PALS'],
    ('PA', 'OD'): ['PA_PALS'],
    ('PA', 'OP'): ['PA_PALS'],
    ('PA', 'OT'): ['PA_PALS'],
    ('PA', 'PH'): ['PA_PALS'],
    ('PA', 'PN'): ['PA_PALS'],
    ('PA', 'PT'): ['PA_PALS'],
    ('PA', 'RNA'): ['PA_PALS'],
    ('PA', 'SH'): ['PA_PALS'],
    ('PA', 'SW'): ['PA_PALS'],

    # RI
    ('RI', 'ABA'): ['RI_HEALTH'],
    ('RI', 'AP'): ['RI_HEALTH'],
    ('RI', 'AU'): ['RI_HEALTH'],
    ('RI', 'CP'): ['RI_HEALTH', 'PSYPACT'],
    ('RI', 'DAC'): ['RI_HEALTH'],
    ('RI', 'DC'): ['RI_HEALTH'],
    ('RI', 'DO'): ['RI_HEALTH'],
    ('RI', 'DT'): ['RI_HEALTH'],
    ('RI', 'LC'): ['IBCLC_COMMISSION', 'RI_HEALTH'],
    ('RI', 'LPC'): ['RI_HEALTH'],
    ('RI', 'MD'): ['RI_HEALTH'],
    ('RI', 'MW'): ['RI_HEALTH'],
    ('RI', 'NP'): ['RI_HEALTH'],
    ('RI', 'NPB'): ['RI_HEALTH'],
    ('RI', 'OD'): ['RI_HEALTH'],
    ('RI', 'OP'): ['RI_HEALTH'],
    ('RI', 'OT'): ['RI_HEALTH'],
    ('RI', 'PA'): ['RI_HEALTH'],
    ('RI', 'PAS'): ['RI_HEALTH'],
    ('RI', 'PH'): ['RI_HEALTH'],
    ('RI', 'PN'): ['RI_HEALTH'],
    ('RI', 'PT'): ['RI_HEALTH'],
    ('RI', 'RNA'): ['RI_HEALTH'],
    ('RI', 'SH'): ['RI_HEALTH'],
    ('RI', 'SW'): ['RI_HEALTH'],

    # SC
    # SC LPC and SW boards at verify.llronline.com require reCAPTCHA v2 â€” blocked in CAPTCHA_PROV_TYPES.
    # SC_SCLLR_LPCMFT / SC_SCLLR_SW are out-of-state telehealth registries only (TLC/TLS format).
    ('SC', 'LC'): ['IBCLC_COMMISSION', 'SC_SCLLR_LPCMFT'],
    ('SC', 'LPC'): ['SC_SCLLR_LPCMFT'],
    ('SC', 'SW'): ['SC_SCLLR_SW'],

    # SD
    ('SD', 'AU'): ['SD_AUDIOLOGY'],
    ('SD', 'CP'): ['SD_PSYCH'],
    ('SD', 'DC'): ['SD_CHIRO'],
    ('SD', 'OD'): ['SD_OPT'],
    ('SD', 'OP'): ['SD_OPT'],
    ('SD', 'PT'): ['SD_PT'],
    ('SD', 'SH'): ['SD_SPEECH'],

    # TX
    ('TX', 'AP'): ['TX_MEDBOARD'],
    ('TX', 'CP'): ['TX_BHEC'],
    ('TX', 'DA'): ['TX_DENTAL'],
    ('TX', 'DAC'): ['TX_CHEMICAL'],
    ('TX', 'DC'): ['TX_CHIRO'],
    ('TX', 'DDS'): ['TX_DENTAL'],
    ('TX', 'DMD'): ['TX_DENTAL'],
    ('TX', 'DO'): ['TX_MEDBOARD'],
    ('TX', 'LPC'): ['TX_BHEC'],
    ('TX', 'MD'): ['TX_MEDBOARD'],
    ('TX', 'MST'): ['TX_BHEC'],
    ('TX', 'MT'): ['TX_TDLR'],
    ('TX', 'NP'): ['TX_MEDBOARD'],
    ('TX', 'NPB'): ['TX_MEDBOARD'],
    ('TX', 'NPS'): ['TX_MEDBOARD'],
    ('TX', 'OD'): ['TX_OPTOMETRY'],
    ('TX', 'OP'): ['TX_OPTOMETRY'],
    ('TX', 'PA'): ['TX_MEDBOARD'],
    ('TX', 'PAB'): ['TX_MEDBOARD'],
    ('TX', 'PAS'): ['TX_MEDBOARD'],
    ('TX', 'PN'): ['TX_MEDBOARD'],
    ('TX', 'RN'): ['TX_MEDBOARD'],
    ('TX', 'RNA'): ['TX_MEDBOARD'],
    ('TX', 'SW'): ['TX_BHEC'],

    # VA
    ('VA', 'ABA'): ['VA_DHP'],
    ('VA', 'AP'): ['VA_DHP'],
    ('VA', 'AU'): ['VA_DHP'],
    ('VA', 'CP'): ['VA_DHP'],
    ('VA', 'DC'): ['VA_DHP'],
    ('VA', 'DDS'): ['VA_DHP'],
    ('VA', 'DMD'): ['VA_DHP'],
    ('VA', 'DO'): ['VA_DHP'],
    ('VA', 'DP'): ['VA_DHP'],
    # ('VA', 'DT') intentionally omitted â€” VA does not license DT/NUT (certification only); no_routing â†’ Skip/N/A
    ('VA', 'GNC'): ['VA_DHP'],
    ('VA', 'LC'): ['IBCLC_COMMISSION', 'VA_DHP'],
    ('VA', 'LPC'): ['VA_DHP'],
    ('VA', 'MD'): ['VA_DHP'],
    ('VA', 'MT'): ['VA_DHP'],
    ('VA', 'MW'): ['VA_DHP'],
    ('VA', 'NP'): ['VA_DHP'],
    ('VA', 'NPB'): ['VA_DHP'],
    ('VA', 'NPS'): ['VA_DHP'],
    # ('VA', 'NUT') intentionally omitted â€” VA does not license DT/NUT (certification only); no_routing â†’ Skip/N/A
    ('VA', 'OD'): ['VA_DHP'],
    ('VA', 'OP'): ['VA_DHP'],
    ('VA', 'OT'): ['VA_DHP'],
    ('VA', 'PA'): ['VA_DHP'],
    ('VA', 'PAB'): ['VA_DHP'],
    ('VA', 'PAS'): ['VA_DHP'],
    ('VA', 'PH'): ['VA_DHP'],
    ('VA', 'PN'): ['VA_DHP'],
    ('VA', 'PT'): ['VA_DHP'],
    ('VA', 'RNA'): ['VA_DHP'],
    ('VA', 'SH'): ['VA_DHP'],
    ('VA', 'SW'): ['VA_DHP'],

    # VT
    ('VT', 'CP'): ['VT_OPR'],
    ('VT', 'DC'): ['VT_OPR'],
    ('VT', 'DO'): ['VT_MEDBOARD'],
    ('VT', 'DP'): ['VT_OPR'],
    ('VT', 'DT'): ['VT_OPR'],
    ('VT', 'LAC'): ['VT_OPR'],
    ('VT', 'LC'): ['IBCLC_COMMISSION', 'VT_OPR'],
    ('VT', 'LPC'): ['VT_OPR'],
    ('VT', 'MD'): ['VT_MEDBOARD'],
    ('VT', 'NP'): ['VT_OPR'],
    ('VT', 'OD'): ['VT_OPR'],
    ('VT', 'OP'): ['VT_OPR'],
    ('VT', 'OT'): ['VT_OPR'],
    ('VT', 'PA'): ['VT_MEDBOARD'],
    ('VT', 'PAS'): ['VT_MEDBOARD'],
    ('VT', 'PH'): ['VT_MEDBOARD'],
    ('VT', 'PN'): ['VT_OPR'],
    ('VT', 'PT'): ['VT_OPR'],
    ('VT', 'SW'): ['VT_OPR'],

    # WA
    ('WA', 'ABA'): ['WA_HEALTH'],
    ('WA', 'AU'): ['WA_HEALTH'],
    ('WA', 'CP'): ['WA_HEALTH'],
    ('WA', 'DAC'): ['WA_HEALTH'],
    ('WA', 'DDS'): ['WA_HEALTH'],
    ('WA', 'DMD'): ['WA_HEALTH'],
    ('WA', 'DO'): ['WA_HEALTH'],
    ('WA', 'DP'): ['WA_HEALTH'],
    ('WA', 'DT'): ['WA_HEALTH'],
    ('WA', 'LC'): ['IBCLC_COMMISSION', 'WA_HEALTH'],
    ('WA', 'LPC'): ['WA_HEALTH'],
    ('WA', 'MD'): ['WA_HEALTH'],
    ('WA', 'MST'): ['WA_HEALTH'],
    ('WA', 'MT'): ['WA_HEALTH'],
    ('WA', 'MW'): ['WA_HEALTH'],
    ('WA', 'ND'): ['WA_HEALTH'],
    ('WA', 'NP'): ['WA_HEALTH'],
    ('WA', 'NPB'): ['WA_HEALTH'],
    ('WA', 'NUT'): ['WA_HEALTH'],
    ('WA', 'OP'): ['WA_HEALTH'],
    ('WA', 'OT'): ['WA_HEALTH'],
    ('WA', 'PA'): ['WA_HEALTH'],
    ('WA', 'PAS'): ['WA_HEALTH'],
    ('WA', 'PH'): ['WA_HEALTH'],
    ('WA', 'PM'): ['WA_HEALTH'],
    ('WA', 'PN'): ['WA_HEALTH'],
    ('WA', 'PT'): ['WA_HEALTH'],
    ('WA', 'RNA'): ['WA_HEALTH'],
    ('WA', 'SH'): ['WA_HEALTH'],
    ('WA', 'SW'): ['WA_HEALTH'],

    # WI
    ('WI', 'ABA'): ['WI_DSPS'],
    ('WI', 'AU'): ['WI_DSPS'],
    ('WI', 'CP'): ['WI_DSPS'],
    ('WI', 'DC'): ['WI_DSPS'],
    ('WI', 'DDS'): ['WI_DSPS'],
    ('WI', 'DMD'): ['WI_DSPS'],
    ('WI', 'DO'): ['WI_DSPS'],
    ('WI', 'DP'): ['WI_DSPS'],
    ('WI', 'DT'): ['WI_DSPS'],
    ('WI', 'LC'): ['IBCLC_COMMISSION', 'WI_DSPS'],
    ('WI', 'LPC'): ['WI_DSPS'],
    ('WI', 'MD'): ['WI_DSPS'],
    ('WI', 'MT'): ['WI_DSPS'],
    ('WI', 'NP'): ['WI_DSPS'],
    ('WI', 'NPB'): ['WI_DSPS'],
    ('WI', 'OD'): ['WI_DSPS'],
    ('WI', 'OP'): ['WI_DSPS'],
    ('WI', 'OT'): ['WI_DSPS'],
    ('WI', 'PA'): ['WI_DSPS'],
    ('WI', 'PAB'): ['WI_DSPS'],
    ('WI', 'PAS'): ['WI_DSPS'],
    ('WI', 'PH'): ['WI_DSPS'],
    ('WI', 'PN'): ['WI_DSPS'],
    ('WI', 'PT'): ['WI_DSPS'],
    ('WI', 'RN'): ['WI_DSPS'],
    ('WI', 'RNA'): ['WI_DSPS'],
    ('WI', 'SH'): ['WI_DSPS'],
    ('WI', 'SW'): ['WI_DSPS'],

    # WV
    ('WV', 'CP'): ['WV_PSYCH'],
    ('WV', 'DA'): ['WV_DENTAL'],
    ('WV', 'DC'): ['WV_CHIRO'],
    ('WV', 'DDS'): ['WV_DENTAL'],
    ('WV', 'DMD'): ['WV_DENTAL'],
    ('WV', 'DO'): ['WV_MEDBOARD_MD'],
    ('WV', 'MD'): ['WV_MEDBOARD_MD'],
    ('WV', 'OD'): ['WV_OPTOMETRY'],
    ('WV', 'OP'): ['WV_OPTOMETRY'],
    ('WV', 'PA'): ['WV_MEDBOARD_PA'],
    ('WV', 'PAS'): ['WV_MEDBOARD_PA'],
    ('WV', 'PT'): ['WV_PT'],
    ('WV', 'SW'): ['WV_SOCIALWORK'],

    # WY
    ('WY', 'AP'): ['WY_PHYSICIAN'],
    ('WY', 'AU'): ['WY_SPEECH'],
    ('WY', 'CP'): ['WY_PSYCH'],
    ('WY', 'DA'): ['WY_DENTAL'],
    ('WY', 'DAC'): ['WY_MENTAL_HEALTH'],
    ('WY', 'DC'): ['WY_CHIRO'],
    ('WY', 'DDS'): ['WY_DENTAL'],
    ('WY', 'DMD'): ['WY_DENTAL'],
    ('WY', 'DO'): ['WY_PHYSICIAN'],
    ('WY', 'DT'): ['WY_DIETETICS'],
    ('WY', 'LC'): ['IBCLC_COMMISSION', 'WY_MENTAL_HEALTH'],
    ('WY', 'LPC'): ['WY_MENTAL_HEALTH'],
    ('WY', 'MD'): ['WY_PHYSICIAN'],
    ('WY', 'NP'): ['WY_PHYSICIAN'],
    ('WY', 'OD'): ['WY_OPTOMETRY'],
    ('WY', 'OP'): ['WY_OPTOMETRY'],
    ('WY', 'OT'): ['WY_OT'],
    ('WY', 'PA'): ['WY_PA'],
    ('WY', 'PAS'): ['WY_PA'],
    ('WY', 'PH'): ['WY_PHYSICIAN'],
    ('WY', 'PN'): ['WY_PHYSICIAN'],
    ('WY', 'PT'): ['WY_PT'],
    ('WY', 'RNA'): ['WY_PHYSICIAN'],
    ('WY', 'SH'): ['WY_SPEECH'],
    ('WY', 'SW'): ['WY_MENTAL_HEALTH'],

}
# fmt: on
